import { RiVoiceprintFill } from "react-icons/ri";
import Head from "next/head";
import { useEffect, useState } from "react";
import { getSession, signIn } from "next-auth/react";
import Router from "next/router";

const login = () => {
  const [fields, setFields] = useState({
    username: "",
    password: "",
  });
  function fieldHandler(e) {
    e.preventDefault(e);
    const name = e.target.getAttribute("name");
    setFields({ ...fields, [name]: e.target.value });
  }
  async function submitHandler(e) {
    e.preventDefault();
    const res = await signIn("credentials", {
      username: fields.username,
      password: fields.password,
      callbackUrl: "/dashboard",
    });
    console.log(res);
  }

  async function checkSession() {
    const session = await getSession();
    if (session) return Router.push("/dashboard");
    return;
  }
  useEffect(() => {
    checkSession();
  }, []);
  return (
    <>
      <Head>
        <title>Larasati Keu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col justify-center px-6 py-12 lg:px-8 min-w-full bg-slate-800">
        <div className="sm:mx-auto sm:w-full sm:max-w-sm">
          <RiVoiceprintFill className="mx-auto h-10 w-auto text-slate-100" />

          <h2 className="mt-10 text-center text-2xl font-bold leading-9 tracking-tight text-slate-100">
            Login
          </h2>
        </div>
        <div className="mt-10 sm:mx-auto sm:w-full sm:max-w-sm">
          <form className="space-y-6" onSubmit={submitHandler.bind(this)}>
            <div>
              <label
                htmlFor="username"
                className="block text-sm font-medium leading-6 text-slate-100"
              >
                Username
              </label>
              <div className="mt-2">
                <input
                  onChange={fieldHandler.bind(this)}
                  id="username"
                  name="username"
                  type="username"
                  autoComplete="username"
                  required
                  className="block w-full rounded-md border-0 px-2 py-1.5 text-slate-900 shadow-sm ring-1 ring-inset ring-slate-300 placeholder:text-slate-400 focus:ring-2 focus:ring-inset focus:ring-slate-600 sm:text-sm sm:leading-6"
                />
              </div>
            </div>
            <div>
              <div className="flex items-center justify-between">
                <label
                  htmlFor="password"
                  className="block text-sm font-medium leading-6 text-slate-100"
                >
                  Password
                </label>
              </div>
              <div className="mt-2">
                <input
                  onChange={fieldHandler.bind(this)}
                  id="password"
                  name="password"
                  type="password"
                  autoComplete="current-password"
                  required
                  className="block w-full rounded-md border-0 px-2 py-1.5 text-slate-900 shadow-sm ring-1 ring-inset ring-slate-300 placeholder:text-slate-400 focus:ring-2 focus:ring-inset focus:ring-slate-600 sm:text-sm sm:leading-6"
                />
              </div>
            </div>
            <div>
              <button
                type="submit"
                className="flex w-full justify-center rounded-md bg-slate-600 px-3 py-1.5 text-sm font-semibold leading-6 text-white shadow-sm hover:bg-slate-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-slate-600"
              >
                Sign in
              </button>
            </div>
          </form>
        </div>
      </div>
    </>
  );
};

export default login;
